import { TUser } from 'shared-types/dist'
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm'
import 'reflect-metadata'

/**
 * Represents the user entity inside the database.
 */
@Entity()
export class User implements TUser {
    /**
     * The id for the user is an autogenerated uuid.
     */
    @PrimaryGeneratedColumn('uuid')
    id!: string

    /**
     * The username for the user.
     */
    @Column()
    username: string

    /**
     * The password for the user.
     */
    @Column()
    password: string

    constructor(username: string, password: string) {
        this.username = username
        this.password = password
    }
}